### ISSUE TITLE
Unity examples not working at all.

### ISSUE THREAD

**Issue by slawo** [ashoulson/VolatilePhysics#16]
Hi, I was about to test the library using Unity 4.7.0.

Unfortunately the scenes are empty.

Also Activating VOLATILE_UNITY creates numerous bugs and stops the project from compiling.

Is there a stable version I could use to do some testing?

**Comment by ashoulson** [comment]
All of the Volatile demos are done in Unity 5. I'm not sure about how backwards compatibility will work with the scenes. I'll check on the VOLATILE_UNITY flag though. Could you post the errors? You may need to add the UnityEngine.dll to your project if you're building against it for Unity compatibility.

**Comment by slawo** [comment]
OK! Thank you for pointing that out. Just tried the demos with unity 5 and yes they work.

As to the errors it's mostly missing functions like Assert and Co implemented in VolatileEngine.Debug but not in UnityEngine.Debug...

Also:

`Assets/__TEST/VolatilePhysics-master/VolatilePhysics/Body.cs(74,41): error CS0121: The call is ambiguous between the following methods or properties: `Volatile.VolatileUtil.InvRotate(this UnityEngine.Vector2, UnityEngine.Vector2)' and `Volatile.VolatileUtil.InvRotate(this UnityEngine.Vector2, UnityEngine.Vector2)'`
