### ISSUE TITLE
Is this repository still maintained?

### ISSUE THREAD

**Issue by Atlinx** [ashoulson/VolatilePhysics#26]
I noticed that the last commented issue dates back to 2016, so I was wondering if this repository is still maintained.

**Comment by ashoulson** [comment]
Unfortunately not, I'm not in a position to make changes at the moment. Sorry about that! There are a number of forks though.

**Comment by Atlinx** [comment]
Ah, that's unfortunate. Your repository is still a really great starting point for networked physics engines nonetheless! The code is readable, and I managed to get collision layers, kinematic bodies, and triggers working after a few modifications.
